---
- hosts: all
  sudo: yes
  tasks:
   - name: execute commands
     shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     name: install ce
     shell: yum install -y docker-ce
     name: setenforce to 0
     shell: setenforce 0
     name: disable selinux
     shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
