- hosts: sgp-ans01
  become: yes
  tasks:
    - name: create the 'pureuser' user
      user: name=pureuser append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'pureuser' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'pureuser ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the pureuser user
      authorized_key: user=pureuser key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
