---
- name:
  hosts: flasharray
  gather_facts: no
  connection: local
  tasks: 
    - name: Make host ansibledemolin01 with iSCSI ports
      purefa_host:
        host: ansibledemolin0
        protocol: iscsi
        iqn:
         - iqn.2019-05.com.redhat:5f244ba6eab6
        fa_url: 10.226.224.110
        api_token: aa009fd2-7686-7d48-8698-26b7eb2ae841

